In [2]:
API_key='b9de1d23cbaaa6467aa06710caf5a3bd'

In [3]:
import requests,json

In [55]:
def get_coordinates():
    api_key='b9de1d23cbaaa6467aa06710caf5a3bd'
    city=input("enter city name")
    #request_url=f'http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api_key}'
    request_url='http://api.openweathermap.org/geo/1.0/direct?q='+city+'&appid='+api_key
    response=requests.get(request_url)
    coordinates=response.json()
    print(coordinates)
get_coordinates()

enter city name bhavnagar

[{'name': 'Bhavnagar', 'local_names': {'bn': 'ভাবনগর', 'uk': 'Бхавнагар', 'ml': 'ഭാവ്നഗർ', 'he': 'בהונאגר', 'ps': 'باونگر', 'ar': 'بهاونقر', 'fa': 'باونگر', 'pa': 'ਭਾਵਨਗਰ', 'kn': 'ಭಾವನಗರ', 'ja': 'バーヴナガル', 'ru': 'Бхавнагар', 'te': 'భావ్\u200cనగర్', 'gu': 'ભાવનગર', 'mr': 'भावनगर', 'sr': 'Бавнагар', 'ne': 'भावनगर', 'ur': 'بھاؤ نگر', 'es': 'Bhavnagar', 'de': 'Bhavnagar', 'ta': 'பவநகர்', 'hi': 'भावनगर', 'zh': '巴夫那加'}, 'lat': 21.7718836, 'lon': 72.1416449, 'country': 'IN', 'state': 'Gujarat'}]

In [56]:
def get_coordinates():
    api_key='b9de1d23cbaaa6467aa06710caf5a3bd'
    city=input("enter city name")
    #request_url=f'http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api_key}'
    request_url='http://api.openweathermap.org/geo/1.0/direct?q='+city+'&appid='+api_key
    response=requests.get(request_url)
    coordinates=response.json()
    #print(json.dumps(coordinates,indent=5))
    lattitude=coordinates[0]['lat']
    longitude=coordinates[0]['lon']
    return lattitude,longitude,city
lat,lon,city=get_coordinates()
print(city,": Lattitude and Longitude")
print("--------------------------------")
print("Lattitude:",lat)
print("Longitude:",lon)

enter city name bhavnagar

bhavnagar : Lattitude and Longitude
--------------------------------
Lattitude: 21.7718836
Longitude: 72.1416449

In [60]:
def current_whether_data():
    api_key='b9de1d23cbaaa6467aa06710caf5a3bd'
    request_url=f'https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid='+api_key
    response=requests.get(request_url)
    weather_data=response.json()
    print(json.dumps(weather_data,indent=5))
    description=weather_data['weather'][0]['description']
    temp=weather_data['main']['temp']
    pressure=weather_data['main']['pressure']
    humidity=weather_data['main']['humidity']
    wind_speed=weather_data['wind']['speed']
    visibility=weather_data['visibility']
    print("current weather data of ",city)
    print("--------------------------------")
    print("weather description",description)
    print("temp",temp)
    print("pressure",pressure)
    print("humidity",humidity)
    print("wind_speed",wind_speed)
    print("visibility",visibility)
current_whether_data()

{
     "coord": {
          "lon": 72.1416,
          "lat": 21.7719
     },
     "weather": [
          {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
          }
     ],
     "base": "stations",
     "main": {
          "temp": 306.66,
          "feels_like": 311.46,
          "temp_min": 306.66,
          "temp_max": 306.66,
          "pressure": 1010,
          "humidity": 53,
          "sea_level": 1010,
          "grnd_level": 1007
     },
     "visibility": 10000,
     "wind": {
          "speed": 2.96,
          "deg": 276,
          "gust": 3.26
     },
     "clouds": {
          "all": 0
     },
     "dt": 1779682074,
     "sys": {
          "country": "IN",
          "sunrise": 1779668972,
          "sunset": 1779716848
     },
     "timezone": 19800,
     "id": 1276032,
     "name": "Bhavnagar",
     "cod": 200
}
current weather data of  bhavnagar
--------------------------------
weather description clear sky
temp 306.66
pressure 1010
humidity 53
wind_speed 2.96
visibility 10000

In [59]:
def air_pollution():
    api_key='b9de1d23cbaaa6467aa06710caf5a3bd'
    request_url=f'http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={lon}&appid='+api_key
    response=requests.get(request_url)
    air_pollution=response.json()
    print(json.dumps(air_pollution,indent=5))
    aqi=air_pollution['list'][0]['main']['aqi']
    print("aqi-index",aqi)
    aqi_dict={1:"good",2:"Fair",3:"Moderate",4:"Poor",5:"Very Poor"}
    print("quality",aqi_dict[aqi])
air_pollution()

{
     "coord": {
          "lon": 72.1416,
          "lat": 21.7719
     },
     "list": [
          {
               "main": {
                    "aqi": 1
               },
               "components": {
                    "co": 85.05,
                    "no": 0.13,
                    "no2": 0.42,
                    "o3": 29.86,
                    "so2": 0.74,
                    "pm2_5": 1.62,
                    "pm10": 4.15,
                    "nh3": 0.31
               },
               "dt": 1779682076
          }
     ]
}
aqi-index 1
quality good

In [111]:
def weather_forecast():
    api_key='b9de1d23cbaaa6467aa06710caf5a3bd'
    city=input("enter city name")
    #request_url=f'http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api_key}'
    request_url1='http://api.openweathermap.org/geo/1.0/direct?q='+city+'&appid='+api_key
    response1=requests.get(request_url1)
    coordinates=response1.json()
    lat=coordinates[0]['lat']
    lon=coordinates[0]['lon']
    print(lat,lon)
    request_url2=f'https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid='+api_key
    response2=requests.get(request_url2)
    five_day=response2.json()
    print(json.dumps(five_day,indent=5))
    data={"date_time":[],"temperature":[],"pressure":[],"humidity":[],"wind_speed":[],"visibility":[],"description":[]}
    for i in five_day['list']:
        data["date_time"].append(i['dt_txt'])
        data["temperature"].append(i['main']['temp'])
        data["pressure"].append(i['main']['pressure'])
        data["humidity"].append(i['main']['humidity'])
        data["wind_speed"].append(i['wind']['speed'])
        data["description"].append(i['weather'][0]['description'])
        data["visibility"].append(i['visibility'])
    print(data)
    import pandas as pd
    df=pd.DataFrame(data)
    print(df)
weather_forecast()

enter city name bhavnagar

21.7718836 72.1416449
{
     "cod": "200",
     "message": 0,
     "cnt": 40,
     "list": [
          {
               "dt": 1779688800,
               "main": {
                    "temp": 309,
                    "feels_like": 314.22,
                    "temp_min": 309,
                    "temp_max": 309,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 1006,
                    "humidity": 46,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 1.8,
                    "deg": 209,
                    "gust": 4.75
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-25 06:00:00"
          },
          {
               "dt": 1779699600,
               "main": {
                    "temp": 309.65,
                    "feels_like": 314.89,
                    "temp_min": 309.65,
                    "temp_max": 310.95,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 44,
                    "temp_kf": -1.3
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.46,
                    "deg": 165,
                    "gust": 7.09
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-25 09:00:00"
          },
          {
               "dt": 1779710400,
               "main": {
                    "temp": 310.31,
                    "feels_like": 315.99,
                    "temp_min": 310.31,
                    "temp_max": 310.96,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 43,
                    "temp_kf": -0.65
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 7.4,
                    "deg": 183,
                    "gust": 8.63
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-25 12:00:00"
          },
          {
               "dt": 1779721200,
               "main": {
                    "temp": 308.18,
                    "feels_like": 313.9,
                    "temp_min": 308.18,
                    "temp_max": 308.18,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1003,
                    "humidity": 50,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 3,
                    "deg": 227,
                    "gust": 8.06
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-25 15:00:00"
          },
          {
               "dt": 1779732000,
               "main": {
                    "temp": 306.47,
                    "feels_like": 308.94,
                    "temp_min": 306.47,
                    "temp_max": 306.47,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1005,
                    "humidity": 46,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.09,
                    "deg": 272,
                    "gust": 8.21
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-25 18:00:00"
          },
          {
               "dt": 1779742800,
               "main": {
                    "temp": 304.73,
                    "feels_like": 307.69,
                    "temp_min": 304.73,
                    "temp_max": 304.73,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1004,
                    "humidity": 54,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.36,
                    "deg": 244,
                    "gust": 5.61
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-25 21:00:00"
          },
          {
               "dt": 1779753600,
               "main": {
                    "temp": 302.93,
                    "feels_like": 305.95,
                    "temp_min": 302.93,
                    "temp_max": 302.93,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1004,
                    "humidity": 62,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.62,
                    "deg": 261,
                    "gust": 6.67
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-26 00:00:00"
          },
          {
               "dt": 1779764400,
               "main": {
                    "temp": 304.73,
                    "feels_like": 307.69,
                    "temp_min": 304.73,
                    "temp_max": 304.73,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 1006,
                    "humidity": 54,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.11,
                    "deg": 256,
                    "gust": 6.04
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-26 03:00:00"
          },
          {
               "dt": 1779775200,
               "main": {
                    "temp": 309.78,
                    "feels_like": 312.14,
                    "temp_min": 309.78,
                    "temp_max": 309.78,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1005,
                    "humidity": 36,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 3.1,
                    "deg": 205,
                    "gust": 5.43
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-26 06:00:00"
          },
          {
               "dt": 1779786000,
               "main": {
                    "temp": 312.01,
                    "feels_like": 315.76,
                    "temp_min": 312.01,
                    "temp_max": 312.01,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 1002,
                    "humidity": 34,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 3.46,
                    "deg": 184,
                    "gust": 6.5
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-26 09:00:00"
          },
          {
               "dt": 1779796800,
               "main": {
                    "temp": 312.9,
                    "feels_like": 315.8,
                    "temp_min": 312.9,
                    "temp_max": 312.9,
                    "pressure": 1003,
                    "sea_level": 1003,
                    "grnd_level": 1000,
                    "humidity": 30,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.13,
                    "deg": 226,
                    "gust": 6.89
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-26 12:00:00"
          },
          {
               "dt": 1779807600,
               "main": {
                    "temp": 309.53,
                    "feels_like": 312.7,
                    "temp_min": 309.53,
                    "temp_max": 309.53,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 1002,
                    "humidity": 39,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.6,
                    "deg": 286,
                    "gust": 8.43
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-26 15:00:00"
          },
          {
               "dt": 1779818400,
               "main": {
                    "temp": 306.37,
                    "feels_like": 309.59,
                    "temp_min": 306.37,
                    "temp_max": 306.37,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1004,
                    "humidity": 49,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.88,
                    "deg": 263,
                    "gust": 9.24
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-26 18:00:00"
          },
          {
               "dt": 1779829200,
               "main": {
                    "temp": 304.1,
                    "feels_like": 307.65,
                    "temp_min": 304.1,
                    "temp_max": 304.1,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1003,
                    "humidity": 59,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.39,
                    "deg": 242,
                    "gust": 7.12
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-26 21:00:00"
          },
          {
               "dt": 1779840000,
               "main": {
                    "temp": 302.31,
                    "feels_like": 306.43,
                    "temp_min": 302.31,
                    "temp_max": 302.31,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1004,
                    "humidity": 71,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.34,
                    "deg": 247,
                    "gust": 6.75
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-27 00:00:00"
          },
          {
               "dt": 1779850800,
               "main": {
                    "temp": 304.59,
                    "feels_like": 308.68,
                    "temp_min": 304.59,
                    "temp_max": 304.59,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 1006,
                    "humidity": 59,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.03,
                    "deg": 266,
                    "gust": 5.98
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-27 03:00:00"
          },
          {
               "dt": 1779861600,
               "main": {
                    "temp": 309.17,
                    "feels_like": 312.69,
                    "temp_min": 309.17,
                    "temp_max": 309.17,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1005,
                    "humidity": 41,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 3.16,
                    "deg": 202,
                    "gust": 5.24
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-27 06:00:00"
          },
          {
               "dt": 1779872400,
               "main": {
                    "temp": 311.94,
                    "feels_like": 316.5,
                    "temp_min": 311.94,
                    "temp_max": 311.94,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1003,
                    "humidity": 36,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 3.45,
                    "deg": 179,
                    "gust": 6.32
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-27 09:00:00"
          },
          {
               "dt": 1779883200,
               "main": {

In [102]:
api_key='b9de1d23cbaaa6467aa06710caf5a3bd'
request_url2=f'https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid='+api_key
response2=requests.get(request_url2)
five_day=response2.json()
json.dumps(five_day,indent=5)
data={"date_time":[],"temperature":[],"pressure":[],"humidity":[],"wind_speed":[],"visibility":[],"description":[]}
for i in five_day['list']:
    data["date_time"].append(i['dt_txt'])
    data["temperature"].append(i['main']['temp'])
    data["pressure"].append(i['main']['pressure'])
    data["humidity"].append(i['main']['humidity'])
    data["wind_speed"].append(i['wind']['speed'])
    data["description"].append(i['weather'][0]['description'])
    data["visibility"].append(i['visibility'])

import pandas as pd
df=pd.DataFrame(data)
df

,date_time,temperature,pressure,humidity,wind_speed,visibility,description
0,2026-05-25 06:00:00,309.00,1009,46,1.80,10000,clear sky
1,2026-05-25 09:00:00,309.65,1008,44,4.46,10000,clear sky
2,2026-05-25 12:00:00,310.31,1006,43,7.40,10000,clear sky
3,2026-05-25 15:00:00,308.18,1005,50,3.00,10000,clear sky
4,2026-05-25 18:00:00,306.47,1007,46,6.09,10000,clear sky
5,2026-05-25 21:00:00,304.73,1007,54,4.36,10000,clear sky
6,2026-05-26 00:00:00,302.93,1007,62,4.62,10000,clear sky
7,2026-05-26 03:00:00,304.73,1009,54,5.11,10000,clear sky
8,2026-05-26 06:00:00,309.78,1008,36,3.10,10000,clear sky
9,2026-05-26 09:00:00,312.01,1004,34,3.46,10000,clear sky
10,2026-05-26 12:00:00,312.90,1003,30,4.13,10000,clear sky
11,2026-05-26 15:00:00,309.53,1004,39,6.60,10000,clear sky
12,2026-05-26 18:00:00,306.37,1007,49,6.88,10000,clear sky
13,2026-05-26 21:00:00,304.10,1006,59,5.39,10000,clear sky
14,2026-05-27 00:00:00,302.31,1007,71,4.34,10000,clear sky
15,2026-05-27 03:00:00,304.59,1009,59,5.03,10000,clear sky
16,2026-05-27 06:00:00,309.17,1008,41,3.16,10000,clear sky
17,2026-05-27 09:00:00,311.94,1005,36,3.45,10000,clear sky
18,2026-05-27 12:00:00,313.10,1003,31,6.24,10000,clear sky
19,2026-05-27 15:00:00,309.44,1005,39,5.14,10000,clear sky
20,2026-05-27 18:00:00,306.32,1008,52,6.55,10000,clear sky
21,2026-05-27 21:00:00,304.04,1007,62,6.49,10000,clear sky
22,2026-05-28 00:00:00,302.30,1007,73,6.81,10000,clear sky
23,2026-05-28 03:00:00,304.93,1009,57,6.94,10000,clear sky
24,2026-05-28 06:00:00,309.98,1008,37,3.06,10000,clear sky
25,2026-05-28 09:00:00,312.47,1005,36,4.10,10000,clear sky
26,2026-05-28 12:00:00,311.59,1003,38,9.32,10000,clear sky
27,2026-05-28 15:00:00,309.88,1005,35,9.19,10000,clear sky
28,2026-05-28 18:00:00,304.96,1007,59,7.65,10000,clear sky
29,2026-05-28 21:00:00,303.17,1006,68,6.71,10000,clear sky
30,2026-05-29 00:00:00,302.13,1007,74,6.08,10000,clear sky
31,2026-05-29 03:00:00,304.51,1009,60,7.01,10000,clear sky
32,2026-05-29 06:00:00,310.72,1007,35,5.67,10000,clear sky
33,2026-05-29 09:00:00,314.18,1003,28,5.52,10000,clear sky
34,2026-05-29 12:00:00,313.90,1002,27,7.58,10000,clear sky
35,2026-05-29 15:00:00,309.92,1003,33,9.59,10000,clear sky
36,2026-05-29 18:00:00,304.49,1005,60,8.85,10000,clear sky
37,2026-05-29 21:00:00,302.53,1004,74,7.86,10000,clear sky
38,2026-05-30 00:00:00,301.96,1005,78,7.97,10000,clear sky
39,2026-05-30 03:00:00,304.87,1006,60,9.33,10000,clear sky

In [112]:
import requests
import pandas as pd
url="https://api.nasa.gov/planetary/apod"
responses=requests.get(url,params={"api_key":"","date":"2026-05-22"})
data=responses.json()
print(data)

{'error': {'code': 'API_KEY_MISSING', 'message': 'No api_key was supplied. Get one at https://api.nasa.gov:443'}}

In [113]:
import requests
import pandas as pd
url="https://api.nasa.gov/planetary/apod?api_key="+api_key
responses=requests.get(url,params={'count':10})
data=responses.json()
print(data)

[{'date': '2020-12-16', 'explanation': "What's the matter with the Bullet Cluster? This massive cluster of galaxies (1E 0657-558) creates gravitational lens distortions of background galaxies in a way that has been interpreted as strong evidence for the leading theory: that dark matter exists within. Different analyses, though, indicate that a less popular alternative -- modifying gravity-- could explain cluster dynamics without dark matter, and provide a more likely progenitor scenario as well. Currently, the two scientific hypotheses are competing to explain the observations: it's invisible matter versus amended gravity. The duel is dramatic as a clear Bullet-proof example of dark matter would shatter the simplicity of modified gravity theories.  The featured sonified image is a Hubble/Chandra/Magellan composite with red depicting the X-rays emitted by hot gas, and blue depicting the suggested separated dark matter distribution.  The sonification assigns low tones to dark matter, mid-range frequencies to visible light, and high tones to X-rays.  The battle over the matter in the Bullet cluster is likely to continue as more observations, computer simulations, and analyses are completed.    Submitted to APOD: Notable images of the 2020 Geminids Meteor Shower", 'media_type': 'video', 'service_version': 'v1', 'title': 'Sonified: The Matter of the Bullet Cluster', 'url': 'https://www.youtube.com/embed/sau5-39wK1c?rel=0'}, {'copyright': 'W. Keel, UA', 'date': '1996-07-23', 'explanation': "Shining brightly, the mighty Jupiter rules this gorgeous Kodacolor photo of the Milky Way near Sagittarius. Astronomer Bill Keel took the picture earlier this month (July 7) while standing near the summit of Hawaii's Mauna Kea contemplating the sky in the direction of the center of the Galaxy (right of picture center). In addition to the gas giant planet, which is well placed for evening viewing, the image contains an impressive sampler of celestial goodies. Many famous emission nebulae are visible as reddish patches - M16, the Eagle nebula, is just above and right of center, with the Horseshoe nebula, M17, just below it and farther to the right. Also, look for the Lagoon Nebula, M8, as the brightest red patch at the right of the picture with the Trifid Nebula, M20, just above it and to the left. The milky glow of distant unresolved stars in the plane of our Galaxy (thus the term Milky Way) runs through the image cut by dark, absorbing, interstellar dust clouds. The much anticipated comet Hale-Bopp is also clearly visible. Where's the comet? Click on the picture to view the comet's location flanked by superposed vertical lines. The comet was discovered while still beyond the orbit of Jupiter a year ago today independently by Alan Hale and Thomas Bopp. Astronomers monitoring Hale-Bopp's activity report that having now brightened to almost 6th magnitude it is still on track for becoming an extremely bright naked-eye comet in early 1997.", 'hdurl': 'https://apod.nasa.gov/apod/image/hb_keel2_lines.gif', 'media_type': 'image', 'service_version': 'v1', 'title': 'Hale-Bopp, Jupiter, and the Milky Way', 'url': 'https://apod.nasa.gov/apod/image/hb_keel2.gif'}, {'date': '1998-02-17', 'explanation': 'even years ago the brightest supernova of modern times was recorded. Now the expanding debris from this tremendous stellar explosion is seen to be crashing into previously expelled material.  The onset of this collision is shown by the arrow in the above picture as the yellow spot on the interior of the ring.  Although the collision is occurring at speeds near 60 million km/hour, it will appear to take years due to the vast distances involved. As the supernova blast wave moves out, it shock-heats any gas it encounters, causing it to glow.  Astronomers are thus hopeful that the blast wave will illuminate the interesting past of SN 1987a, and perhaps provide more clues about the origins of the mysterious rings.', 'hdurl': 'https://apod.nasa.gov/apod/image/9802/sn87aknot_hst_big.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Shocked by Supernova 1987a', 'url': 'https://apod.nasa.gov/apod/image/9802/sn87aknot_hst.jpg'}, {'date': '2015-11-22', 'explanation': "This moon is doomed. Mars, the red planet named for the Roman god of war, has two tiny moons, Phobos and Deimos, whose names are derived from the Greek for Fear and Panic. These martian moons may well be captured asteroids originating in the main asteroid belt between Mars and Jupiter or perhaps from even more distant reaches of the Solar System. The larger moon, Phobos, is indeed seen to be a cratered, asteroid-like object in this stunning color image from the robotic Mars Reconnaissance Orbiter, recorded at a resolution of about seven meters per pixel. But Phobos orbits so close to Mars - about 5,800 kilometers above the surface compared to 400,000 kilometers for our Moon - that gravitational tidal forces are dragging it down. A recent analysis of the long grooves indicates that they may result from global stretching caused by tides -- the differing force of Mars' gravity on different sides of Phobos.  These grooves may then be an early phase in the disintegration of Phobos into a ring of debris around Mars.   Follow APOD on: Facebook,  Google Plus, or Twitter", 'hdurl': 'https://apod.nasa.gov/apod/image/1511/Phobos_MRO_3374.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Phobos: Doomed Moon of Mars', 'url': 'https://apod.nasa.gov/apod/image/1511/Phobos_MRO_960.jpg'}, {'date': '2024-12-11', 'explanation': "What's the closest active galaxy to planet Earth? That would be Centaurus A, cataloged as NGC 5128, which is only 12 million light-years distant. Forged in a collision of two otherwise normal galaxies, Centaurus A shows several distinctive features including a dark dust lane across its center, outer shells of stars and gas, and jets of particles shooting out from a supermassive black hole at its center.  The featured image captures all of these in a composite series of visible light images totaling over 310 hours captured over the past 10 years with a homebuilt telescope operating in Auckland, New Zealand. The brightness of Cen A's center from low-energy radio waves to high-energy gamma rays underlies its designation as an active galaxy.    Astrophysicists: Browse 3,500+ codes in the Astrophysics Source Code Library", 'hdurl': 'https://apod.nasa.gov/apod/image/2412/CenAShellsJets_Olsen_6150.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'The Shells and Jets of Galaxy Centaurus A', 'url': 'https://apod.nasa.gov/apod/image/2412/CenAShellsJets_Olsen_1080.jpg'}, {'date': '2016-01-03', 'explanation': 'On some nights, the sky is the best show in town. On this night, the sky was not only the best show in town, but a composite image of the sky won an international competition for landscape astrophotography. The featured winning image was taken in 2011 over J�kuls�rl�n, the largest glacial lake in Iceland.  The photographer combined six exposures to capture not only two green auroral rings, but their reflections off the serene lake. Visible in the distant background sky is the band of our Milky Way Galaxy and the Andromeda galaxy. A powerful coronal mass ejection from the Sun caused auroras to be seen as far south as Wisconsin, USA.  Solar activity over the past week has resulted in auroras just over the past few days.   Follow APOD on: Facebook,  Google Plus, or Twitter', 'hdurl': 'https://apod.nasa.gov/apod/image/1601/aurora_vetter_2000.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'A Starry Night of Iceland', 'url': 'https://apod.nasa.gov/apod/image/1601/aurora_vetter_1080.jpg'}, {'date': '1998-05-31', 'explanation': 'Phobos is doomed. Mars, the red planet named for the Roman god of war, has two tiny moons, Phobos and Deimos, whose names are derived from the Greek for Fear and Panic. These Martian moons may well be captured asteroids originating in the asteroid belt between Mars and Jupiter or perhaps from even more distant reaches of the Solar System. In this 1977 Viking orbiter image, the largest moon, Phobos, is seen to be a heavily cratered asteroid-like object. It is about 17 miles across and zips through the Martian sky completing an orbit in less than 8 hours. Phobos orbits so close to Mars, (about 3,600 miles above the surface compared to 250,000 miles for our Moon) that gravitational tidal forces are dragging it down. In 100 million years or so it should crash into the surface or be shattered by stress caused by the relentless tidal forces, the debris forming a ring around Mars.', 'hdurl': 'https://apod.nasa.gov/apod/image/phobos.gif', 'media_type': 'image', 'service_version': 'v1', 'title': 'Phobos: Doomed Moon of Mars', 'url': 'https://apod.nasa.gov/apod/image/phobos.gif'}, {'copyright': 'Jan Curtis \n(U. Alaska), \nACRC', 'date': '1999-11-02', 'explanation': "A night sky can glow in fascinating ways.  Through a clearing in the woods, the pictured sky above Alaska shines by reflected light from a nearby city, by the brightness of the Moon, and by aurora.  The night sky in or near a city appears to contain relatively few stars because lights there reflect off atmospheric particles, hiding stars in a diffuse glow.  The bright Moon also creates a diffuse sky glow, although much less bright than the analogous blue-sky glow created during the day by the Sun.  Particles from the Sun crashing into the Earth's atmosphere are seen here as bands of aurora.  These glows also illuminate visible clouds.  Auroral displays are becoming more frequent as the Sun approaches Solar Maximum.", 'hdurl': 'https://apod.nasa.gov/apod/image/9911/auroramoon_curtis.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Aurora Through a Moonlit Sky', 'url': 'https://apod.nasa.gov/apod/image/9911/auroramoon_curtis_big.jpg'}, {'copyright': 'Rogelio Bernal Andreo', 'date': '2014-07-27', 'explanation': "The clouds surrounding the star system Rho Ophiuchi compose one of the closest star forming regions.  Rho Ophiuchi itself is a binary star system visible in the light-colored region on the image right. The star system, located only 400 light years away, is distinguished by its colorful surroundings, which include a red emission nebula and numerous light and dark brown dust lanes. Near the upper right of the Rho Ophiuchi molecular cloud system is the yellow star Antares, while a distant but coincidently-superposed globular cluster of stars, M4, is visible between Antares and the red emission nebula. Near the image bottom lies IC 4592, the Blue Horsehead nebula.  The blue glow that surrounds the Blue Horsehead's eye -- and other stars around the image -- is a reflection nebula composed of fine dust. On the above image left is a geometrically angled reflection nebula cataloged as Sharpless 1.  Here, the bright star near the dust vortex creates the light of surrounding reflection nebula. Although most of these features are visible through a small telescope pointed toward the constellations of Ophiuchus, Scorpius, and Sagittarius, the only way to see the intricate details of the dust swirls, as featured above, is to use a long exposure camera.", 'hdurl': 'https://apod.nasa.gov/apod/image/1407/RhoOphWide_andreo_2048.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Rho Ophiuchi Wide Field', 'url': 'https://apod.nasa.gov/apod/image/1407/RhoOphWide_andreo_960.jpg'}, {'date': '2026-05-17', 'explanation': "Across the center of this spiral galaxy is a bar.  And at the center of this bar is smaller spiral.  And at the center of that spiral is a supermassive black hole.  This all happens in the big, beautiful, barred spiral galaxy cataloged as NGC 1300, a galaxy that lies some 70 million light-years away toward the constellation of the river Eridanus. This Hubble Space Telescope composite view of the gorgeous island universe is one of the most detailed Hubble images ever made of a complete galaxy.  NGC 1300 spans over 100,000 light-years and the Hubble image reveals striking details of the galaxy's dominant central bar and majestic spiral arms. How the giant bar formed, how it remains, and how it affects star formation remains an active topic of research.   Jigsaw Universe: Astronomy Puzzle of the Day", 'hdurl': 'https://apod.nasa.gov/apod/image/2605/NGC1300_HST_6637.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'NGC 1300: Barred Spiral Galaxy', 'url': 'https://apod.nasa.gov/apod/image/2605/NGC1300_HST_1080.jpg'}]

In [2]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
response=requests.get(url)
print(response.status_code)
data=response.json()
print(json.dumps(data,indent=5))

200
{
     "userId": 1,
     "id": 1,
     "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
     "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

In [4]:
print(type(response.json()))

<class 'dict'>

In [5]:
print(type(response.text))

<class 'str'>

In [6]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts"
response=requests.get(url)
print(response.status_code)
data=response.json()
print(json.dumps(data,indent=5))

200
[
     {
          "userId": 1,
          "id": 1,
          "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
          "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
     },
     {
          "userId": 1,
          "id": 2,
          "title": "qui est esse",
          "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
     },
     {
          "userId": 1,
          "id": 3,
          "title": "ea molestias quasi exercitationem repellat qui ipsa sit aut",
          "body": "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut"
     },
     {
          "userId": 1,
          "id": 4,
          "title": "eum et est occaecati",
          "body": "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit"
     },
     {
          "userId": 1,
          "id": 5,
          "title": "nesciunt quas odio",
          "body": "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque"
     },
     {
          "userId": 1,
          "id": 6,
          "title": "dolorem eum magni eos aperiam quia",
          "body": "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae"
     },
     {
          "userId": 1,
          "id": 7,
          "title": "magnam facilis autem",
          "body": "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas"
     },
     {
          "userId": 1,
          "id": 8,
          "title": "dolorem dolore est ipsam",
          "body": "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae"
     },
     {
          "userId": 1,
          "id": 9,
          "title": "nesciunt iure omnis dolorem tempora et accusantium",
          "body": "consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas"
     },
     {
          "userId": 1,
          "id": 10,
          "title": "optio molestias id quia eum",
          "body": "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error"
     },
     {
          "userId": 2,
          "id": 11,
          "title": "et ea vero quia laudantium autem",
          "body": "delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi"
     },
     {
          "userId": 2,
          "id": 12,
          "title": "in quibusdam tempore odit est dolorem",
          "body": "itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio"
     },
     {
          "userId": 2,
          "id": 13,
          "title": "dolorum ut in voluptas mollitia et saepe quo animi",
          "body": "aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam"
     },
     {
          "userId": 2,
          "id": 14,
          "title": "voluptatem eligendi optio",
          "body": "fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum"
     },
     {
          "userId": 2,
          "id": 15,
          "title": "eveniet quod temporibus",
          "body": "reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae"
     },
     {
          "userId": 2,
          "id": 16,
          "title": "sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio",
          "body": "suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta"
     },
     {
          "userId": 2,
          "id": 17,
          "title": "fugit voluptas sed molestias voluptatem provident",
          "body": "eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo"
     },
     {
          "userId": 2,
          "id": 18,
          "title": "voluptate et itaque vero tempora molestiae",
          "body": "eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam"
     },
     {
          "userId": 2,
          "id": 19,
          "title": "adipisci placeat illum aut reiciendis qui",
          "body": "illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas"
     },
     {
          "userId": 2,
          "id": 20,
          "title": "doloribus ad provident suscipit at",
          "body": "qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo"
     },
     {
          "userId": 3,
          "id": 21,
          "title": "asperiores ea ipsam voluptatibus modi minima quia sint",
          "body": "repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt"
     },
     {
          "userId": 3,
          "id": 22,
          "title": "dolor sint quo a velit explicabo quia nam",
          "body": "eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse"
     },
     {
          "userId": 3,
          "id": 23,
          "title": "maxime id vitae nihil numquam",
          "body": "veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis"
     },
     {
          "userId": 3,
          "id": 24,
          "title": "autem hic labore sunt dolores incidunt",
          "body": "enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt"
     },
     {
          "userId": 3,
          "id": 25,
          "title": "rem alias distinctio quo quis",
          "body": "ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio"
     },
     {
          "userId": 3,
          "id": 26,
          "title": "est et quae odit qui non",
          "body": "similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero"
     },
     {
          "userId": 3,
          "id": 27,
          "title": "quasi id et eos tenetur aut quo autem",
          "body": "eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur"
     },
     {
          "userId": 3,
          "id": 28,
          "title": "delectus ullam et corporis nulla voluptas sequi",
          "body": "non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum"
     },
     {
          "userId": 3,
          "id": 29,
          "title": "iusto eius quod necessitatibus culpa ea",
          "body": "odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores"
     },
     {
          "userId": 3,
          "id": 30,
          "title": "a quo magni similique perferendis",
          "body": "alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia"
     },
     {
          "userId": 4,
          "id": 31,
          "title": "ullam ut quidem id aut vel consequuntur",
          "body": "debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae"
     },
     {
          "userId": 4,
          "id": 32,
          "title": "doloremque illum aliquid sunt",
          "body": "deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime"
     },
     {
          "userId": 4,
          "id": 33,
          "title": "qui explicabo molestiae dolorem",
          "body": "rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod"
     },
     {
          "userId": 4,
          "id": 34,
          "title": "magnam ut rerum iure",
          "body": "ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis"
     },
     {
          "userId": 4,
          "id": 35,
          "title": "id nihil consequatur molestias animi provident",
          "body": "nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit"
     },
     {
          "userId": 4,
          "id": 36,
          "title": "fuga nam accusamus voluptas reiciendis itaque",
          "body": "ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore"
     },
     {
          "userId": 4,
          "id": 37,
          "title": "provident vel ut sit ratione est",
          "body": "debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui"
     },
     {
          "userId": 4,
          "id": 38,
          "title": "explicabo et eos deleniti nostrum ab id repellendus",
          "body": "animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure"
     },
     {
          "userId": 4,
          "id": 39,
          "title": "eos dolorem iste accusantium est eaque quam",
          "body": "corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex"
     },
     {
          "userId": 4,
          "id": 40,
          "title": "enim quo cumque",
          "body": "ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam"
     },
     {
          "userId": 5,
          "id": 41,
          "title": "non est facere",
          "body": "molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe"
     },
     {
          "userId": 5,
          "id": 42,
          "title": "commodi ullam sint et excepturi error explicabo praesentium voluptas",
          "body": "odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut"
     },
     {
          "userId": 5,
          "id": 43,
          "title": "eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis",
          "body": "similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis"
     },
     {
          "userId": 5,
          "id": 44,
          "title": "optio dolor molestias sit",
          "body": "temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae"
     },
     {
          "userId": 5,
          "id": 45,
          "title": "ut numquam possimus omnis eius suscipit laudantium iure",
          "body": "est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem"
     },
     {
          "userId": 5,
          "id": 46,
          "title": "aut quo modi neque nostrum ducimus",
          "body": "voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid"
     },
     {
          "userId": 5,
          "id": 47,
          "title": "quibusdam cumque rem aut deserunt",
          "body": "voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate"
     },
     {
          "userId": 5,
          "id": 48,
          "title": "ut voluptatem illum ea doloribus itaque eos",
          "body": "voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit"
     },
     {
          "userId": 5,
          "id": 49,
          "title": "laborum non sunt aut ut assumenda perspiciatis voluptas",
          "body": "inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut"
     },
     {
          "userId": 5,
          "id": 50,
          "title": "repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem",
          "body": "error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur"
     },
     {
          "userId": 6,
          "id": 51,
          "title": "soluta aliquam aperiam consequatur illo quis voluptas",
          "body": "sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem"
     },
     {
          "userId": 6,
          "id": 52,
          "title": "qui enim et consequuntur quia animi quis voluptate quibusdam",
          "body": "iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum"
     },
     {
          "userId": 6,
          "id": 53,
          "title": "ut quo aut ducimus alias",
          "body": "minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique"
     },
     {
          "userId": 6,
          "id": 54,
          "title": "sit asperiores ipsam eveniet odio non quia",
          "body": "totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia"
     },
     {
          "userId": 6,
          "id": 55,
          "title": "sit vel voluptatem et non libero",
          "body": "debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit"
     },
     {
          "userId": 6,
          "id": 56,
          "title": "qui et at rerum necessitatibus",
          "body": "aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi"
     },
     {
          "userId": 6,
          "id": 57,
          "title": "sed ab est est",
          "body": "at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est"
     },
     {
          "userId": 6,
          "id": 58,
          "title": "voluptatum itaque dolores nisi et quasi",
          "body": "veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam"
     },
     {
          "userId": 6,
          "id": 59,
          "title": "qui commodi dolor at maiores et quis id accusantium",
          "body": "perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt"
     },
     {
          "userId": 6,
          "id": 60,
          "title": "consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere",
          "body": "asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis"
     },
     {
          "userId": 7,
          "id": 61,
          "title": "voluptatem doloribus consectetur est ut ducimus",
          "body": "ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit"
     },
     {
          "userId": 7,
          "id": 62,
          "title": "beatae enim quia vel",
          "body": "enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio"
     },
     {
          "userId": 7,
          "id": 63,
          "title": "voluptas blanditiis repellendus animi ducimus error sapiente et suscipit",
          "body": "enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta"
     },
     {
          "userId": 7,
          "id": 64,
          "title": "et fugit quas eum in in aperiam quod",
          "body": "id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui"
     },
     {
          "userId": 7,
          "id": 65,
          "title": "consequatur id enim sunt et et",
          "body": "voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur"
     },
     {

In [7]:
for i in data[:5]:
    print(i['id'],"-",i['title'])

1 - sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2 - qui est esse
3 - ea molestias quasi exercitationem repellat qui ipsa sit aut
4 - eum et est occaecati
5 - nesciunt quas odio

In [9]:
for i in data[:15:2]:
    print(i['id'],"-",i['title'])

1 - sunt aut facere repellat provident occaecati excepturi optio reprehenderit
3 - ea molestias quasi exercitationem repellat qui ipsa sit aut
5 - nesciunt quas odio
7 - magnam facilis autem
9 - nesciunt iure omnis dolorem tempora et accusantium
11 - et ea vero quia laudantium autem
13 - dolorum ut in voluptas mollitia et saepe quo animi
15 - eveniet quod temporibus

In [12]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts"
params={'userId':1}
response=requests.get(url,params=params)
print(response.status_code)
data=response.json()
#print(json.dumps(data,indent=5))
print(len(data))

200
10

In [14]:
response.url

'https://jsonplaceholder.typicode.com/posts?userId=1'

In [18]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
headers={'User-Agent':'Mozilla/5.0','accept':'application/json'}
response=requests.get(url,headers=headers)
print(response.status_code)
data=response.json()
print(json.dumps(data,indent=5))

200
{
     "userId": 1,
     "id": 1,
     "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
     "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

In [21]:
response.headers['date']

'Sat, 30 May 2026 06:30:13 GMT'

In [29]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts"
new_post={
    'title':'Learning Requests',
    'body':'this is tutorial',
    'userId':1
}
response=requests.post(url,json=new_post)
print(response.status_code)
print(response.json())

201
{'title': 'Learning Requests', 'body': 'this is tutorial', 'userId': 1, 'id': 101}

In [30]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
new_post={
    'title':'updated title',
    'body':'updatede tutorial',
    'userId':1
}
response=requests.put(url,json=new_post)
print(response.status_code)
print(response.json())

200
{'title': 'updated title', 'body': 'updatede tutorial', 'userId': 1, 'id': 1}

In [33]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
new_post={
    'title':'updated title',   
}
response=requests.put(url,json=new_post)
print(response.status_code)
print(response.json())

200
{'title': 'updated title', 'id': 1}

In [34]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
new_post={
    'title':'patched title',   
}
response=requests.patch(url,json=new_post)
print(response.status_code)
print(response.json())

200
{'userId': 1, 'id': 1, 'title': 'patched title', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [35]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
response=requests.delete(url)
print(response.status_code)
print(response.json())

200
{}

In [42]:
import requests
import json
url="https://picsum.photos/200"
response = requests.get(url)
with open('random_images.jpg','wb') as f:
    f.write(response.content)
print("image downloaded")

image downloaded

In [39]:
import requests
import json
url="https://picsum.photos/id/237/200/300"
response = requests.get(url)
with open('random_images.jpg','wb') as f:
    f.write(response.content)
print("image downloaded")

image downloaded

In [45]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
response=requests.get(url)
data=response.json()
with open('post.json','w') as f:
    json.dump(data,f,indent=5)
print('json file saved')

json file saved

In [47]:
with open('post.json','r') as f:
    load_data = json.load(f)
    print(load_data)

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [48]:
import requests
import json
import pandas as pd
url="https://jsonplaceholder.typicode.com/posts"
response=requests.get(url)
data=response.json()
df=pd.DataFrame(data)
df

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

In [12]:
import requests
import json
def users():
    url="https://jsonplaceholder.typicode.com/users/1"
    response=requests.get(url)
    data=response.json()
    uid=data['id']
    name=data['name']
    uname=data['username']
    email=data['email']
    street=data['address']['street']
    suite=data['address']['suite']
    city=data['address']['city']
    zcode=data['address']['zipcode']
    address=street+" "+suite+" "+city+" "+zcode
    lat=data['address']['geo']['lat']
    lon=data['address']['geo']['lng']
    print("name",name)
    print("username",uname)
    print("email",email)
    print("address",address)
    print("lattitude",lat)
    print('longitude',lon)
users()

name Leanne Graham
username Bret
email Sincere@april.biz
address Kulas Light Apt. 556 Gwenborough 92998-3874
lattitude -37.3159
longitude 81.1496

In [19]:
import requests
import json
def users():
    url="https://jsonplaceholder.typicode.com/users"
    response=requests.get(url)
    data=response.json()
    for i in users:
        uid=i['id']
        name=i['name']
        uname=i['username']
        email=i['email']
        street=i['address']['street']
        suite=i['address']['suite']
        city=i['address']['city']
        zcode=i['address']['zipcode']
        address=street+" "+suite+" "+city+" "+zcode
        lat=i['address']['geo']['lat']
        lon=i['address']['geo']['lng']
        print("name",name)
        print("username",uname)
        print("email",email)
        print("address",address)
        print("lattitude",lat)
        print('longitude',lon)
users()

TypeError: 'function' object is not iterable

In [16]:
json_string='''{
"name":"alice",
"age":"30"
}'''
data=json.loads(json_string)
print(data)
print(type(json_string))
print(type(data))

{'name': 'alice', 'age': '30'}
<class 'str'>
<class 'dict'>

In [24]:
json_string={
"name":"alice",
"age":"30"
}
data=json.dumps(json_string,indent=5)
print(data)
print(type(json_string))
print(type(data))

{
     "name": "alice",
     "age": "30"
}
<class 'dict'>
<class 'str'>

In [39]:
import requests
import json
import pandas as pd
url="https://jsonplaceholder.typicode.com/posts"
params={
    '_page':1,
    '_limit':5
}
response=requests.get(url,params=params)
data=response.json()
#print(json.dumps(data,indent=5))
for i in data:
    print(i['id'],"-",i['title'])

1 - sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2 - qui est esse
3 - ea molestias quasi exercitationem repellat qui ipsa sit aut
4 - eum et est occaecati
5 - nesciunt quas odio

In [38]:
import requests
import json
import pandas as pd
url="https://jsonplaceholder.typicode.com/posts"
params={
    '_page':2,
    '_limit':10
}
response=requests.get(url,params=params)
data=response.json()
#print(json.dumps(data,indent=5))
for i in data:
    print(i['id'],"-",i['title'])

11 - et ea vero quia laudantium autem
12 - in quibusdam tempore odit est dolorem
13 - dolorum ut in voluptas mollitia et saepe quo animi
14 - voluptatem eligendi optio
15 - eveniet quod temporibus
16 - sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio
17 - fugit voluptas sed molestias voluptatem provident
18 - voluptate et itaque vero tempora molestiae
19 - adipisci placeat illum aut reiciendis qui
20 - doloribus ad provident suscipit at

In [35]:
import requests
import json
import pandas as pd
url="https://jsonplaceholder.typicode.com/posts"
params={
    '_page':10,
    '_limit':10
}
response=requests.get(url,params=params)
data=response.json()
#print(json.dumps(data,indent=5))
for i in data:
    print(i['id'],"-",i['title'])

91 - aut amet sed
92 - ratione ex tenetur perferendis
93 - beatae soluta recusandae
94 - qui qui voluptates illo iste minima
95 - id minus libero illum nam ad officiis
96 - quaerat velit veniam amet cupiditate aut numquam ut sequi
97 - quas fugiat ut perspiciatis vero provident
98 - laboriosam dolor voluptates
99 - temporibus sit alias delectus eligendi possimus magni
100 - at nam consequatur ea labore ea harum

In [42]:
import requests
import json
import pandas as pd
url="https://jsonplaceholder.typicode.com/posts"
page=1
while page<=3:
    params={
        '_page':page,
        '_limit':10
    }
    response=requests.get(url,params=params)
    data=response.json()
    #print(json.dumps(data,indent=5))
    for i in data:
        print(i['id'],"-",i['title'])
    page+=1

1 - sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2 - qui est esse
3 - ea molestias quasi exercitationem repellat qui ipsa sit aut
4 - eum et est occaecati
5 - nesciunt quas odio
6 - dolorem eum magni eos aperiam quia
7 - magnam facilis autem
8 - dolorem dolore est ipsam
9 - nesciunt iure omnis dolorem tempora et accusantium
10 - optio molestias id quia eum
11 - et ea vero quia laudantium autem
12 - in quibusdam tempore odit est dolorem
13 - dolorum ut in voluptas mollitia et saepe quo animi
14 - voluptatem eligendi optio
15 - eveniet quod temporibus
16 - sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio
17 - fugit voluptas sed molestias voluptatem provident
18 - voluptate et itaque vero tempora molestiae
19 - adipisci placeat illum aut reiciendis qui
20 - doloribus ad provident suscipit at
21 - asperiores ea ipsam voluptatibus modi minima quia sint
22 - dolor sint quo a velit explicabo quia nam
23 - maxime id vitae nihil numquam
24 - autem hic labore sunt dolores incidunt
25 - rem alias distinctio quo quis
26 - est et quae odit qui non
27 - quasi id et eos tenetur aut quo autem
28 - delectus ullam et corporis nulla voluptas sequi
29 - iusto eius quod necessitatibus culpa ea
30 - a quo magni similique perferendis

In [46]:
import requests
url="https://jsonplaceholder.typicode.com/posts"
token="my_secreet_token"
headers={'authorization':f"Bearer {token}"}
response=requests.get(url,headers=headers)
print(response.status_code)
print(response.json())

200

In [4]:
import requests
r=requests.get("http://api.github.com/rate_limit")
data=r.json()
print(data)

print('limit: ',data['rate']['limit'])
print('used: ',data['rate']['used'])
print('remaining',data['rate']['remaining'])
print('reset',data['rate']['reset'])

{'resources': {'code_search': {'limit': 60, 'remaining': 58, 'reset': 1780288022, 'used': 2, 'resource': 'code_search'}, 'core': {'limit': 60, 'remaining': 58, 'reset': 1780288022, 'used': 2, 'resource': 'core'}, 'graphql': {'limit': 0, 'remaining': 0, 'reset': 1780288059, 'used': 0, 'resource': 'graphql'}, 'integration_manifest': {'limit': 5000, 'remaining': 5000, 'reset': 1780288059, 'used': 0, 'resource': 'integration_manifest'}, 'search': {'limit': 10, 'remaining': 10, 'reset': 1780284519, 'used': 0, 'resource': 'search'}}, 'rate': {'limit': 60, 'remaining': 58, 'reset': 1780288022, 'used': 2, 'resource': 'core'}}
limit:  60
used:  2
remaining 58
reset 1780288022

In [6]:
import requests
for i in range(70):
    r=requests.get("https://api.github.com/users/octocat")
    print(i+1,r.status_code)
    if r.status_code==403:
        data=r.json()
        if "API rate limit exceeded" in data.get('message',""):
            print('rate limit exceeded')
            print(data['message'])
            break

1 403
rate limit exceeded
API rate limit exceeded for 120.72.91.122. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

In [7]:
from datetime import datetime
import requests
r=requests.get("https://api.github.com/rate_limit")
data=r.json()
reset_stamp=data['rate']['reset']
reset_time=datetime.fromtimestamp(reset_stamp).strftime("%y-%m-%d %H:%M:%S")
print(reset_time)
#strftime=string formated time

26-06-01 09:57:02